services:
  fronAgrosis:
    image: dilsonchimborazo/front_agrosis:1.1.1
    expose:
      - "80"
    env_file:
      - ./frontAgrosis/.env
    volumes:
      - ./update_env.sh:/app/update_env.sh
    depends_on:
      - back-end
    networks:
      - app-network

  back-end:
    image: dilsonchimborazo/backend_agrosis:1.1.1
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./back-end:/app
      - ./wait-for-postgres.sh:/app/wait-for-postgres.sh
    entrypoint: ["/app/wait-for-postgres.sh", "postgres:5432", "--", "/app/entrypoint.sh"]
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  Doc_Tecnica:
    image: dilsonchimborazo/doc_tecnica:1.1.1
    ports:
      - "4321:4321"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - fronAgrosis
      - back-end
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge