services:
  fronAgrosis:
    image: dilsonchimborazo/front_agrosis:1.1.1
    expose:
      - "80"
    env_file:
      - ./frontAgrosis/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - back-end
    networks:
      - app-network

  back-end:
    image: dilsonchimborazo/backend_agrosis:1.1.1
    expose:
      - "8000"
    env_file:
      - .env
    volumes:
      - ./back-end:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - app-network

  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

  Doc_Tecnica:
    image: dilsonchimborazo/doc_tecnica:1.1.1
    ports:
      - "4321:4321"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8085:80"
    volumes:
      - ./frontAgrosis/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      fronAgrosis:
        condition: service_healthy
      back-end:
        condition: service_started
    networks:
      - app-network


volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge