# Generated by Django 5.1.1 on 2025-03-05 02:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('control_fitosanitario', '0001_initial'),
        ('desarrollan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control_fitosanitario',
            name='fk_id_desarrollan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='desarrollan.desarrollan'),
        ),
    ]
