# Generated by Django 5.1.1 on 2025-03-06 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('precio_unidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateField()),
                ('fk_id_produccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='produccion.produccion')),
            ],
        ),
    ]
