# Generated by Django 5.1.1 on 2025-03-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendario_lunar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion_evento', models.TextField()),
                ('evento', models.CharField(max_length=100)),
            ],
        ),
    ]
