# Generated by Django 5.1.1 on 2025-03-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_h', models.CharField(max_length=500)),
                ('fecha_prestamo', models.DateTimeField(max_length=200)),
                ('estado', models.CharField(choices=[('Prestado', 'Prestado'), ('En reparación', 'En reparación'), ('Disponible', 'Disponible')], max_length=50, null=True)),
            ],
        ),
    ]
