# Generated by Django 5.1.1 on 2025-02-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0004_alter_herramientas_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramientas',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Prestado', 'Prestado'), ('En reparación', 'En reparación')], max_length=50, null=True),
        ),
    ]
