# Generated by Django 5.1.1 on 2025-03-06 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimencion', models.IntegerField()),
                ('nombre_lote', models.CharField(max_length=500)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupado', 'ocupado')], max_length=50, null=True)),
                ('fk_id_ubicacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ubicacion.ubicacion')),
            ],
        ),
    ]
