# Generated by Django 5.1.1 on 2025-03-05 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id_produccion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_produccion', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
