# Generated by Django 5.1.1 on 2024-12-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rol', '0002_alter_rol_rol'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuarios',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fk_id_rol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rol.rol'),
        ),
    ]
